spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ai_code_mother?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123
  profiles:
    active: local
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      ttl: 3600
      username: default
      database: 0
  # session 配置
  session:
    redis:
      flush-mode: on_save
    # session 30 天过期
    timeout: 2592000

server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000