spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ai_code_mother?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123
  profiles:
    active: local
server:
  port: 8123
  servlet:
    context-path: /api
